sudo: required

services:
- docker

branches:
  only:
  - master

env:
  global:
  - REGISTRY: registry.blackwoodseven.com
  - IMAGENAME: "$REGISTRY/$TRAVIS_REPO_SLUG"
  - TAG_VERSION: "$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER"
  - TAG_LATEST: latest
  - secure: bjZ47UafG3xzM7Y4SL1KJxnBn8t8UByVunlcrGON4AZ9qiybuLjBHMyGooTLhNIc24/Vt1W5lSRizGSLqbLeK91uhIVnEZJAEWOi3ZPwtm19w2gWLrRJdZJEbcm32qy4VuCrqARF2RVmxssSZlpBNNSlT037Jf8+B0VoYvwYV2bMEze8Xx9250NXpzXzuFF47ivxW/yu36IuCHd8r4BoImNTIhXxUWIRPLFczFEzwX0Oo8D97nyhkdi4TKjz0pQsFY7CNnI6gNX0zl0f+JEsxqlKOv/PgvEW2mVUY/tu2L1kUilXNYYlMiScWMuDbh0/I/AqTHcJaz3GNFiVGl5IxTZWOjN+Ep6ibhk9gW8QrMUpmAOrz2k7o5uG1Km5VNPnq2/PMuPHO+HEEeK2tgoGk3TreG9EvZruQ0xgbDcmp4jZlgxmVi3Dg1Yjy0uyHXvc/kx36QLajjy8jrtWSSkerMxpFJzadsSkzovrYg//w3SneukcURPZSf+MnKfbHzoa7k1RxgXoKHogf1b0rdLYZh1N3gtZdMU+1itc5KeRx2QMNn5LfUwQga6gTg+ArYv+6DRNTxRbuLtbz+BNuM6aCSNVKR1vwyyxy5pFIjALAFkTh3siDwAxnTkcm93b8Cg9ZBlTpXPMm2alfECo9vRHCLyJILksIqwCmTSdLb0tYXY=

before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- docker --version # for verification

before_script:
- docker login -u travis -p "$REGISTRY_PASSWORD" $REGISTRY
- echo "LABEL GIT_COMMIT=$TRAVIS_COMMIT" >> Dockerfile
- echo "LABEL TAG_VERSION=$TAG_VERSION" >> Dockerfile

script:
- >
  docker --version &&
  docker-compose --version &&
  make test compile &&
  docker build -t $IMAGENAME:$TAG_VERSION -t $IMAGENAME:$TAG_LATEST . &&
  docker push $IMAGENAME:$TAG_VERSION &&
  docker push $IMAGENAME:$TAG_LATEST

after_success:
- >
  git config --global user.email "tech@blackwoodseven.com" &&
  git config --global user.name "Travis CI" &&
  git tag -f $TAG_VERSION $TRAVIS_COMMIT &&
  git push --tags

after_failure:
- echo failed

notifications:
  slack:
    secure: TxTips+wSVOERrM4PUjY2ucOtwM6G5VVOkhBv07qYyDYfpVMoGR4Di6hBsEPwEjW3qQsNJGL4xNN9ZsOOSsiw7qpR4dQCyTl58TmxTzCMC51GH1x0sQAppAK48mFBZCfiyrjl8hriTY50vzVJF72/9S2JZoH55kn5s76dz1vISr9Ff3r+clIYhICyzRo6bdlXA/MMjLZ2l10iylnMwABe7VsZ6mIjXR4cDGgGnXfdMgdWPTdQNu5tKQRhhkHCQbygYyqlVf4rtJ5SYOCCOrXDZ/8ALHzZqab4UqQIYPaABbguYzCgtU/IiFJFEw2Oe47a9l+RlLwtb+cOVmIEyoMzjQkAb9ARuqMp9ehCEqwA9mmGrMb0mgrEKjZZG9GxVNguPLO37gdgwKddL2VXF3gC4pfBQmoQ+vIB+7KCEQOA1VWgsZEvrnqo8FNi6MB85xYWquZxvOiHOCHB/TClyIl0hW3a0YTxCF6o5KjIFe0FDNZ9AflH0E6EkVDwVTwmCyVCL4RQUFxlRFw31B/Ht4gTtbS9G3p/5jouXe6aXJLQ64W174DNDtf3fxAZRHPOW9mfA9sqvewCkcyXf9weh+DNPQEYY7skM2xQFEO11ESWd2ZPYhVNk4D5KebyB5qkMbEqz9l/TbH4oz6lPnl0aJkj9zlbpPWx8dSLl2GhcdMxQ0=
